name: Release

on:
  push:
    branches:
      - main
      - 'dev-v3-*'

permissions:
  id-token: write
  contents: read

jobs:
  release:
    uses: cloudscape-design/actions/.github/workflows/release.yml@main
    secrets: inherit
    with:
      publish-packages: lib